### ISSUE TITLE
Errore poco chiaro alla creazione di una newsletter o mancata definizione dei campi obbligatori

### ISSUE THREAD

**Issue by mamico** [PloneGov-IT/rer.newsletter#1]
Se si crea una newsletter senza impostare nulla se non il titolo (l'unico obbligatorio) si ha l'errore:

`Error generic_problem_add_newsletter. status: 0 `

Questo il trace:

```
  File ".../Products.DCWorkflow-2.2.5-py2.7.egg/Products/DCWorkflow/DCWorkflow.py", line 448, in _executeTransition
    old_state = old_sdef.getId()
AttributeError: 'NoneType' object has no attribute 'getId'

```

**Comment by mamico** [comment]
credo che il problema si alegato al fatto che la directory del workflow si chiama newsletter-workflow e non newsletter_workflow come indicato in workflow.xml e in seconda battuta a https://github.com/PloneGov-IT/rer.newsletter/blob/master/src/rer/newsletter/profiles/default/workflows/newsletter-workflow/definition.xml che non riconosco come un workflow di genericsetup plone

**Comment by eikichi18** [comment]
Controllo subito

**Comment by eikichi18** [comment]
xml del workflow della newsletter sistemato, e nome della cartella sistemato
