### ISSUE TITLE
Custom add permission for Newsletter and Message

### ISSUE THREAD

**Issue by cekk** [PloneGov-IT/rer.newsletter#2]
See [rer.news](https://github.com/PloneGov-IT/rer.news) for example.

Things to do:
- [define a new permission](https://github.com/PloneGov-IT/rer.news/blob/master/src/rer/news/configure.zcml#L16)
- [set the permission to content-type](https://github.com/PloneGov-IT/rer.news/blob/master/src/rer/news/profiles/default/types/ERNews.xml#L29)
- [set roles for that permission](https://github.com/PloneGov-IT/rer.news/blob/master/src/rer/news/profiles/default/rolemap.xml)

**Comment by eikichi18** [comment]
Added
